// name,
// email,
// password,
// phone,
// course,
// college,
// age,
// tenth,
// city,
// twelth,
// bachelor,
// specialization,
// college,
// course,
// country,
// work,
// internship,
// social,
// extra,
// fund,
// careergoal,
// familybg,
// other,
// anythingelse,
// consultancy,
// coupon,
// hear,
// resume,
// file,
// selectedValues,

//     name: listener.name,
//       email: listener.email,
//       password: listener.password,
//       phone: listener.phone,
//       course: listener.course,
//       college: listener.college,
//       age: listener.age,
//       tenth: listener.tenth,
//       city: listener.city,
//       twelth: listener.twelth,
//       bachelor: listener.bachelor,
//       specialization: listener.specialization,
//       college: listener.college,
//       course: listener.course,
//       country: listener.country,
//       work: listener.work,
//       internship: listener.internship,
//       social: listener.social,
//       extra: listener.extra,
//       fund: listener.fund,
//       careergoal: listener.careergoal,
//       familybg: listener.familybg,
//       other: listener.other,
//       anythingelse: listener.anythingelse,
//       consultancy: listener.consultancy,
//       coupon: listener.coupon,
//       hear: listener.hear,
//       resume: listener.resume,
//       file: listener.file,
//       selectedValues: listener.selectedValues,
